sylius_admin_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

app_api_testimony:
    resource: |
        section: api
        alias: app.testimony
        templates: SyliusAdminBundle:Crud
        except: ['show']
    prefix: /api/v1
    type: sylius.resource_api
