app_shop_checkout_select_payment:
  path: /select-payment
  methods: [GET, PUT]
  defaults:
    _controller: sylius.controller.order:updateAction
    _sylius:
      event: payment
      flash: false
      template: "@SyliusShop/Checkout/selectPayment.html.twig"
      form: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectPaymentType
      repository:
        method: findCartForSelectingPayment
        arguments:
        - "expr:service('sylius.context.cart').getCart().getId()"
      state_machine:
        graph: sylius_order_checkout
        transition: select_payment
      redirect:
        route: sylius_shop_order_pay
        parameters:
          tokenValue: resource.tokenValue
