# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    app.email_manager:
        public: true
        class: App\EmailManager\AppEmailManager
        arguments: ['@sylius.email_sender']

    app.form.type.testimony:
        class: App\Form\Type\TestimonyType
        arguments: ['%app.model.testimony.class%']

    app.form.type.testimony_translation:
        class: App\Form\Type\TestimonyTranslationType
        arguments: ['%app.model.testimony_translation.class%']

winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                app_confirm_after_payment_selected:
                    on: ["select_payment", "skip_payment"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'complete'", "'sylius_order_checkout'"]

    app_testimony:
        class: App\Entity\Testimony # class of your domain object
        property_path: state            # property of your object holding the actual state (default is "state")
        graph: app_testimony                   # name of the graph (default is "default")
        states:
            - pending_review
            - published
            - rejected
        transitions:
            publish:
                from: [pending_review]
                to: published
            reject:
                from: [pending_review]
                to: rejected
        callbacks:
            after:
                email_on_publish:
                    on:   'publish'
                    do:   ['@app.email_manager', 'sendTestimonyApprovedEmail']
                    args: ['object']

sylius_resource:
    resources:
        app.testimony:
            classes:
                model: App\Entity\Testimony
                form: App\Form\Type\TestimonyType
            translation:
                classes:
                    model: App\Entity\TestimonyTranslation

sylius_grid:
    grids:
        app_admin_testimony:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Testimony
            limits: [30, 12, 48]
            fields:
                title:
                    type: string
                    label: 'Title'
                description:
                    type: string
                state:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

sylius_mailer:
    emails:
        testimony_approved:
            subject: A new testimony has been approved
            template: Email/testimony_approved.html.twig
